### ISSUE TITLE
Fork subquery/subql :roll_eyes: 

### ISSUE THREAD

**Issue by bryanchriswhite** [fetchai/ledger-subquery#40]
### Background

Subquery's graphql API service ([@subql/query](https://github.com/subquery/subql/tree/main/packages/query) on [npm](https://www.npmjs.com/package/@subql/query)) is using [Postgraphile](https://www.graphile.org/postgraphile/) to generate query resolvers. @suql/query also includes the [postgraphile-plugin-connection-filter](https://github.com/) plugin, which can be configured to enable a variety of features.

### Acceptance Criteria

- [x] Fork [subquery/subql](https://github.com/subquery/subql) and the fork add as a git submodule :roll_eyes: (#42)
- [x] Update "graphql-engine" docker compose service to build from local @subql/query in  the submodule (#42)
- [x] Update ["api" deployment template](./k8s/subquery/templates/api/api.deploy.yaml) to build and run the @subql/query in the submodule (#42)
