### ISSUE TITLE
Release v0.1

### ISSUE THREAD

**Issue by ejfitzgerald** [fetchai/ledger-subquery#8]
## Features

- [x] Initial SubQuery attributes fetchai/ecosystem-tasks#43
- [x] Native Transfers - #11
- [ ] ~~Account Balance Tracking - fetchai/ledger-subquery#17~~ - moved to #9 
- [x] Contract Executions - record user interactions with contract #12
- [x] Initial infrastructure code changes - fetchai/ecosystem-tasks#110 (pre-requisites and sandbox sections)

**Comment by bryanchriswhite** [comment]
Blocked by #57
